const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const panelSchemaGroupTwo = new Schema({
    BSFBazar: { type: Schema.Types.Mixed, default: null },
    SitaMorning: { type: Schema.Types.Mixed, default: null },
    KalyanGoldNight: { type: Schema.Types.Mixed, default: null },
    BombayDay: { type: Schema.Types.Mixed, default: null },
    Srilakshmi: { type: Schema.Types.Mixed, default: null },
    MilanBazar: { type: Schema.Types.Mixed, default: null },
    RatanDay: { type: Schema.Types.Mixed, default: null },
    Chandan: { type: Schema.Types.Mixed, default: null },
    Maharashtra: { type: Schema.Types.Mixed, default: null },
    Worli: { type: Schema.Types.Mixed, default: null },
    WorliMumbaiDay: { type: Schema.Types.Mixed, default: null },
    MainMumbaiRK: { type: Schema.Types.Mixed, default: null },
    WorliMumbai: { type: Schema.Types.Mixed, default: null },
    SitaDay: { type: Schema.Types.Mixed, default: null },
    SatyamMumbai: { type: Schema.Types.Mixed, default: null },
    CountryBazar: { type: Schema.Types.Mixed, default: null },
    RoseBazarDay: { type: Schema.Types.Mixed, default: null },
    RoseBazarNight: { type: Schema.Types.Mixed, default: null },
    JantaMorning: { type: Schema.Types.Mixed, default: null },
    CentralBombay: { type: Schema.Types.Mixed, default: null },
    TeenPatti: { type: Schema.Types.Mixed, default: null },
    SuperTime: { type: Schema.Types.Mixed, default: null },
    Bhagyalaxmi: { type: Schema.Types.Mixed, default: null },
    kaali: { type: Schema.Types.Mixed, default: null },
    MainMumbaiNight: { type: Schema.Types.Mixed, default: null },
    SuperMatka: { type: Schema.Types.Mixed, default: null },
    MaharajTime: { type: Schema.Types.Mixed, default: null },
    MaharajDay: { type: Schema.Types.Mixed, default: null },
    MaharajNight: { type: Schema.Types.Mixed, default: null },
    BazarDay: { type: Schema.Types.Mixed, default: null },
    BazarNight: { type: Schema.Types.Mixed, default: null },
    RajdhaniDay: { type: Schema.Types.Mixed, default: null },
    PunaNight: { type: Schema.Types.Mixed, default: null },
    TimeNight: { type: Schema.Types.Mixed, default: null },
    Mohini: { type: Schema.Types.Mixed, default: null },
    MumbaiStar: { type: Schema.Types.Mixed, default: null },
    kalyanBazar: { type: Schema.Types.Mixed, default: null },
    MainBazarMumbai: { type: Schema.Types.Mixed, default: null },
    Mahadevi: { type: Schema.Types.Mixed, default: null },
    SatyamMumbaiEvening: { type: Schema.Types.Mixed, default: null },
    KalyanGold: { type: Schema.Types.Mixed, default: null },
    SitaNight: { type: Schema.Types.Mixed, default: null },
    KamalMorning: { type: Schema.Types.Mixed, default: null },
    KamalDay: { type: Schema.Types.Mixed, default: null },
    KamalNight: { type: Schema.Types.Mixed, default: null },
    RajdhaniSunday: { type: Schema.Types.Mixed, default: null },
    AndhraMorning: { type: Schema.Types.Mixed, default: null },
    AndhraDay: { type: Schema.Types.Mixed, default: null },
    AndhraNight: { type: Schema.Types.Mixed, default: null },
    BombayRajshreeDay: { type: Schema.Types.Mixed, default: null },
    BombayRajshreeNight: { type: Schema.Types.Mixed, default: null },
    MilanBazarMorning: { type: Schema.Types.Mixed, default: null },
    MilanBazarDay: { type: Schema.Types.Mixed, default: null },
    MilanBazarNight: { type: Schema.Types.Mixed, default: null },
    MahadeviMorning: { type: Schema.Types.Mixed, default: null },
    MahadeviNight: { type: Schema.Types.Mixed, default: null },
    RajyogDay: { type: Schema.Types.Mixed, default: null },
    RajyogNight: { type: Schema.Types.Mixed, default: null },
    Gowa: { type: Schema.Types.Mixed, default: null },
    RoyalDay: { type: Schema.Types.Mixed, default: null },
    MumbaiStartMain: { type: Schema.Types.Mixed, default: null },
});

const PanelTwo = mongoose.model('PanelTwo', panelSchemaGroupTwo);

module.exports = PanelTwo;
