const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const panelSchemaGroupFour = new Schema({
    JodiBSFBazar: { type: Schema.Types.Mixed, default: null },
    JodiSitaMorning: { type: Schema.Types.Mixed, default: null },
    JodiKalyanGoldNight: { type: Schema.Types.Mixed, default: null },
    JodiBombayDay: { type: Schema.Types.Mixed, default: null },
    JodiSrilakshmi: { type: Schema.Types.Mixed, default: null },
    JodiMilanBazar: { type: Schema.Types.Mixed, default: null },
    JodiRatanDay: { type: Schema.Types.Mixed, default: null },
    JodiChandan: { type: Schema.Types.Mixed, default: null },
    JodiMaharashtra: { type: Schema.Types.Mixed, default: null },
    JodiWorli: { type: Schema.Types.Mixed, default: null },
    JodiWorliMumbaiDay: { type: Schema.Types.Mixed, default: null },
    JodiMainMumbaiRK: { type: Schema.Types.Mixed, default: null },
    JodiWorliMumbai: { type: Schema.Types.Mixed, default: null },
    JodiSitaDay: { type: Schema.Types.Mixed, default: null },
    JodiSatyamMumbai: { type: Schema.Types.Mixed, default: null },
    JodiCountryBazar: { type: Schema.Types.Mixed, default: null },
    JodiRoseBazarDay: { type: Schema.Types.Mixed, default: null },
    JodiRoseBazarNight: { type: Schema.Types.Mixed, default: null },
    JodiJantaMorning: { type: Schema.Types.Mixed, default: null },
    JodiCentralBombay: { type: Schema.Types.Mixed, default: null },
    JodiTeenPatti: { type: Schema.Types.Mixed, default: null },
    JodiSuperTime: { type: Schema.Types.Mixed, default: null },
    JodiBhagyalaxmi: { type: Schema.Types.Mixed, default: null },
    Jodikaali: { type: Schema.Types.Mixed, default: null },
    JodiMainMumbaiNight: { type: Schema.Types.Mixed, default: null },
    JodiSuperMatka: { type: Schema.Types.Mixed, default: null },
    JodiMaharajTime: { type: Schema.Types.Mixed, default: null },
    JodiMaharajDay: { type: Schema.Types.Mixed, default: null },
    JodiMaharajNight: { type: Schema.Types.Mixed, default: null },
    JodiBazarDay: { type: Schema.Types.Mixed, default: null },
    JodiBazarNight: { type: Schema.Types.Mixed, default: null },
    JodiRajdhaniDay: { type: Schema.Types.Mixed, default: null },
    JodiPunaNight: { type: Schema.Types.Mixed, default: null },
    JodiTimeNight: { type: Schema.Types.Mixed, default: null },
    JodiMohini: { type: Schema.Types.Mixed, default: null },
    JodiMumbaiStar: { type: Schema.Types.Mixed, default: null },
    JodikalyanBazar: { type: Schema.Types.Mixed, default: null },
    JodiMainBazarMumbai: { type: Schema.Types.Mixed, default: null },
    JodiMahadevi: { type: Schema.Types.Mixed, default: null },
    JodiSatyamMumbaiEvening: { type: Schema.Types.Mixed, default: null },
    JodiKalyanGold: { type: Schema.Types.Mixed, default: null },
    JodiSitaNight: { type: Schema.Types.Mixed, default: null },
    JodiKamalMorning: { type: Schema.Types.Mixed, default: null },
    JodiKamalDay: { type: Schema.Types.Mixed, default: null },
    JodiKamalNight: { type: Schema.Types.Mixed, default: null },
    JodiRajdhaniSunday: { type: Schema.Types.Mixed, default: null },
    JodiAndhraMorning: { type: Schema.Types.Mixed, default: null },
    JodiAndhraDay: { type: Schema.Types.Mixed, default: null },
    JodiAndhraNight: { type: Schema.Types.Mixed, default: null },
    JodiBombayRajshreeDay: { type: Schema.Types.Mixed, default: null },
    JodiBombayRajshreeNight: { type: Schema.Types.Mixed, default: null },
    JodiMilanBazarMorning: { type: Schema.Types.Mixed, default: null },
    JodiMilanBazarDay: { type: Schema.Types.Mixed, default: null },
    JodiMilanBazarNight: { type: Schema.Types.Mixed, default: null },
    JodiMahadeviMorning: { type: Schema.Types.Mixed, default: null },
    JodiMahadeviNight: { type: Schema.Types.Mixed, default: null },
    JodiRajyogDay: { type: Schema.Types.Mixed, default: null },
    JodiRajyogNight: { type: Schema.Types.Mixed, default: null },
    JodiGowa: { type: Schema.Types.Mixed, default: null },
    JodiRoyalDay: { type: Schema.Types.Mixed, default: null },
    JodiMumbaiStartMain: { type: Schema.Types.Mixed, default: null },
});

const PanelFour = mongoose.model('PanelFour', panelSchemaGroupFour);

module.exports = PanelFour;
