const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const panelSchemaGroupOne = new Schema({
    Home: { type: Schema.Types.Mixed, default: null },
    MilanMorning: { type: Schema.Types.Mixed, default: null },
    Sridevi: { type: Schema.Types.Mixed, default: null },
    KalyanMorning: { type: Schema.Types.Mixed, default: null },
    Padmavati: { type: Schema.Types.Mixed, default: null },
    Madhuri: { type: Schema.Types.Mixed, default: null },
    SrideviMorning: { type: Schema.Types.Mixed, default: null },
    Maharani: { type: Schema.Types.Mixed, default: null },
    Prabhat: { type: Schema.Types.Mixed, default: null },
    KarnatakDay: { type: Schema.Types.Mixed, default: null },
    TimeBazarMorning: { type: Schema.Types.Mixed, default: null },
    TimeBazar: { type: Schema.Types.Mixed, default: null },
    Diamond: { type: Schema.Types.Mixed, default: null },
    TaraMumbaiDay: { type: Schema.Types.Mixed, default: null },
    MainKalyan: { type: Schema.Types.Mixed, default: null },
    TimeBazarDay: { type: Schema.Types.Mixed, default: null },
    MilanDay: { type: Schema.Types.Mixed, default: null },
    MainBazarDay: { type: Schema.Types.Mixed, default: null },
    PunaBazar: { type: Schema.Types.Mixed, default: null },
    Kalyan: { type: Schema.Types.Mixed, default: null },
    SrideviNight: { type: Schema.Types.Mixed, default: null },
    DiamondNight: { type: Schema.Types.Mixed, default: null },
    MadhuriNight: { type: Schema.Types.Mixed, default: null },
    NightTimeBazar: { type: Schema.Types.Mixed, default: null },
    TaraMumbaiNight: { type: Schema.Types.Mixed, default: null },
    MainBazarNight: { type: Schema.Types.Mixed, default: null },
    MilanNight: { type: Schema.Types.Mixed, default: null },
    RajdhaniNight: { type: Schema.Types.Mixed, default: null },
    MainBazar: { type: Schema.Types.Mixed, default: null },
    MaharaniDay: { type: Schema.Types.Mixed, default: null },
    SrideviDay: { type: Schema.Types.Mixed, default: null },
    Dhanashree: { type: Schema.Types.Mixed, default: null },
    KalyanNight: { type: Schema.Types.Mixed, default: null },
    KalyanPro: { type: Schema.Types.Mixed, default: null },
    Gujarat: { type: Schema.Types.Mixed, default: null },
    OldMainMumbai: { type: Schema.Types.Mixed, default: null },
    RajLaxmi: { type: Schema.Types.Mixed, default: null },
    MadhurMorning: { type: Schema.Types.Mixed, default: null },
    MadhurDay: { type: Schema.Types.Mixed, default: null },
    MadhurNight: { type: Schema.Types.Mixed, default: null },
    RatanKhatri: { type: Schema.Types.Mixed, default: null },
    MaharaniNight: { type: Schema.Types.Mixed, default: null },
    PadmavatiNight: { type: Schema.Types.Mixed, default: null },
    JayShreeDay: { type: Schema.Types.Mixed, default: null },
    SriDhanalaxmi: { type: Schema.Types.Mixed, default: null },
    DhanshreeDay: { type: Schema.Types.Mixed, default: null },
    MainBombay: { type: Schema.Types.Mixed, default: null },
    SundayBazar: { type: Schema.Types.Mixed, default: null },
    SundayBazarNight: { type: Schema.Types.Mixed, default: null },
    SuperGoaDay: { type: Schema.Types.Mixed, default: null },
    PunaNightMain: { type: Schema.Types.Mixed, default: null },
    Khajana: { type: Schema.Types.Mixed, default: null },
    SrideviMain: { type: Schema.Types.Mixed, default: null },
    SrideviMainNight: { type: Schema.Types.Mixed, default: null },
    SupremeMorning: { type: Schema.Types.Mixed, default: null },
    SupremeDay: { type: Schema.Types.Mixed, default: null },
    SupremeNight: { type: Schema.Types.Mixed, default: null },
    GujratNight: { type: Schema.Types.Mixed, default: null },
    DhanaShreeNight: { type: Schema.Types.Mixed, default: null },
});


const PanelOne = mongoose.model('PanelOne', panelSchemaGroupOne);

module.exports = PanelOne;
