const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const panelSchemaGroupThree = new Schema({
    JodiMilanMorning: { type: Schema.Types.Mixed, default: null },
    JodiSridevi: { type: Schema.Types.Mixed, default: null },
    JodiKalyanMorning: { type: Schema.Types.Mixed, default: null },
    JodiPadmavati: { type: Schema.Types.Mixed, default: null },
    JodiMadhuri: { type: Schema.Types.Mixed, default: null },
    JodiSrideviMorning: { type: Schema.Types.Mixed, default: null },
    JodiMaharani: { type: Schema.Types.Mixed, default: null },
    JodiPrabhat: { type: Schema.Types.Mixed, default: null },
    JodiKarnatakDay: { type: Schema.Types.Mixed, default: null },
    JodiTimeBazarMorning: { type: Schema.Types.Mixed, default: null },
    JodiTimeBazar: { type: Schema.Types.Mixed, default: null },
    JodiDiamond: { type: Schema.Types.Mixed, default: null },
    JodiTaraMumbaiDay: { type: Schema.Types.Mixed, default: null },
    JodiMainKalyan: { type: Schema.Types.Mixed, default: null },
    JodiTimeBazarDay: { type: Schema.Types.Mixed, default: null },
    JodiMilanDay: { type: Schema.Types.Mixed, default: null },
    JodiMainBazarDay: { type: Schema.Types.Mixed, default: null },
    JodiPunaBazar: { type: Schema.Types.Mixed, default: null },
    JodiKalyan: { type: Schema.Types.Mixed, default: null },
    JodiSrideviNight: { type: Schema.Types.Mixed, default: null },
    JodiDiamondNight: { type: Schema.Types.Mixed, default: null },
    JodiMadhuriNight: { type: Schema.Types.Mixed, default: null },
    JodiNightTimeBazar: { type: Schema.Types.Mixed, default: null },
    JodiTaraMumbaiNight: { type: Schema.Types.Mixed, default: null },
    JodiMainBazarNight: { type: Schema.Types.Mixed, default: null },
    JodiMilanNight: { type: Schema.Types.Mixed, default: null },
    JodiRajdhaniNight: { type: Schema.Types.Mixed, default: null },
    JodiMainBazar: { type: Schema.Types.Mixed, default: null },
    JodiMaharaniDay: { type: Schema.Types.Mixed, default: null },
    JodiSrideviDay: { type: Schema.Types.Mixed, default: null },
    JodiDhanashree: { type: Schema.Types.Mixed, default: null },
    JodiKalyanNight: { type: Schema.Types.Mixed, default: null },
    JodiKalyanPro: { type: Schema.Types.Mixed, default: null },
    JodiGujarat: { type: Schema.Types.Mixed, default: null },
    JodiOldMainMumbai: { type: Schema.Types.Mixed, default: null },
    JodiRajLaxmi: { type: Schema.Types.Mixed, default: null },
    JodiMadhurMorning: { type: Schema.Types.Mixed, default: null },
    JodiMadhurDay: { type: Schema.Types.Mixed, default: null },
    JodiMadhurNight: { type: Schema.Types.Mixed, default: null },
    JodiRatanKhatri: { type: Schema.Types.Mixed, default: null },
    JodiMaharaniNight: { type: Schema.Types.Mixed, default: null },
    JodiPadmavatiNight: { type: Schema.Types.Mixed, default: null },
    JodiJayShreeDay: { type: Schema.Types.Mixed, default: null },
    JodiSriDhanalaxmi: { type: Schema.Types.Mixed, default: null },
    JodiDhanshreeDay: { type: Schema.Types.Mixed, default: null },
    JodiMainBombay: { type: Schema.Types.Mixed, default: null },
    JodiSundayBazar: { type: Schema.Types.Mixed, default: null },
    JodiSundayBazarNight: { type: Schema.Types.Mixed, default: null },
    JodiSuperGoaDay: { type: Schema.Types.Mixed, default: null },
    JodiPunaNightMain: { type: Schema.Types.Mixed, default: null },
    JodiKhajana: { type: Schema.Types.Mixed, default: null },
    JodiSrideviMain: { type: Schema.Types.Mixed, default: null },
    JodiSrideviMainNight: { type: Schema.Types.Mixed, default: null },
    JodiSupremeMorning: { type: Schema.Types.Mixed, default: null },
    JodiSupremeDay: { type: Schema.Types.Mixed, default: null },
    JodiSupremeNight: { type: Schema.Types.Mixed, default: null },
    JodiGujratNight: { type: Schema.Types.Mixed, default: null },
    JodiDhanaShreeNight: { type: Schema.Types.Mixed, default: null },
});


const PanelThree = mongoose.model('PanelThree', panelSchemaGroupThree);

module.exports = PanelThree;
